### PR TITLE
fix: Removing database support of Employee Scheduling

### LINKED ISSUE #314: feat: Remove database support from the quickstarts
Update the quickstart examples that use database and convert them to use a local approach.

### PR DESCRIPTION
**Pull request by zepfred**
## Description of the change

This PR removes the database support for the `Employee Scheduling` quick start.

Screenshot from 2024-03-01 10-03-28
Screenshot from 2024-03-01 10-04-41
Screenshot from 2024-03-01 10-03-33
Screenshot from 2024-03-01 10-04-12
Screenshot from 2024-03-01 10-04-26
Screenshot from 2024-03-01 10-04-20

### Development

- [x] The changes have been covered with tests, if necessary.
- [x] You have a green build, with the exception of the flaky tests.
- [x] UI and JS files are fully tested, the user interface works for all modules affected by your changes (e.g., solve and analyze buttons).
- [x] The network calls work for all modules affected by your changes (e.g., solving a problem).
- [x] The console messages are validated for all modules affected by your changes.

### Code Review

- [x] This pull request includes an explanatory title and description.
- [x] The GitHub issue is linked.
- [ ] At least one other engineer has approved the changes.
- [ ] After PR is merged, inform the reporter.

### CODE REVIEW

**Review by triceo — CHANGES_REQUESTED** [review]
Something is wrong with the constraints. See that the score is 0/0, yet there are clearly broken constraints.

image

**Comment by zepfred** [comment]
> Something is wrong with the constraints. See that the score is 0/0, yet there are clearly broken constraints.
> 
> image

Good catch! When using JPA, the persistence context ensures that there will be single instances of `Employee`, and they will be equal to `Joiners.equal(Shift::getEmployee, Availability::getEmployee)`. I had to add the `equals` and `hashCode` methods to compare the instances properly.

Screenshot from 2024-03-04 09-26-32

File: use-cases/employee-scheduling/src/main/java/org/acme/employeescheduling/domain/Availability.java [hunk 1]
```diff
@@ -69,4 +62,16 @@ public void setAvailabilityType(AvailabilityType availabilityType) {
...
+    @Override
+    public boolean equals(Object o) {
+        if (this == o) return true;
+        if (!(o instanceof Availability that)) return false;
+        return Objects.equals(getId(), that.getId());
+    }
+
+    @Override
+    public int hashCode() {
+        return Objects.hash(getId());
```
Comment (triceo) [inline use-cases/employee-scheduling/src/main/java/org/acme/employeescheduling/domain/Availability.java]: Let's not use [Objects.hash(...)](https://docs.oracle.com/javase/8/docs/api/java/util/Objects.html#hash-java.lang.Object...-).

This method creates a varargs array on the heap every time it is invoked. When this `hashCode` method gets on a hot path (such as in constraints), this is a considerable slowdown.

Let's not teach people this.

**Review by triceo — APPROVED** [review]

**Review by triceo — APPROVED** [review]
