### PR TITLE
fix: penalizing or rewarding constraints with overlapping time for Employee Scheduling

### LINKED ISSUE #481: Employee scheduling: desired/undesired/unavailable constraints should only penalize the number of overlapping minutes
This demoes poorly

image

Each of these cases they get 16 hours of points, but it should only be 8 hours of points (6hours in the morning, 2 hours in the evening)

- [x] Java
- [x] Python

### PR DESCRIPTION
**Pull request by zepfred**
## Description of the change

This pull request updates the employee-scheduling module constraints to penalize or reward constraints with overlapping time.

## Java
Screenshot from 2024-06-20 16-42-35

## Python 
Screenshot from 2024-06-20 19-40-22

### Development

- [x] The changes have been covered with tests, if necessary.
- [x] You have a green build, with the exception of the flaky tests.
- [x] UI and JS files are fully tested, the user interface works for all modules affected by your changes (e.g., solve and analyze buttons).
- [x] The network calls work for all modules affected by your changes (e.g., solving a problem).
- [x] The console messages are validated for all modules affected by your changes.

### Code Review

- [x] This pull request includes an explanatory title and description.
- [x] The GitHub issue is linked.
- [x] At least one other engineer has approved the changes.
- [ ] After PR is merged, inform the reporter.

### CODE REVIEW

File: java/employee-scheduling/src/main/java/org/acme/employeescheduling/solver/EmployeeSchedulingConstraintProvider.java [hunk 1]
```diff
@@ -76,48 +71,33 @@ Constraint atLeast10HoursBetweenTwoShifts(ConstraintFactory constraintFactory) {
...
         return constraintFactory.forEach(Shift.class)
-                .filter(shift -> {
-                    Set<LocalDate> unavailableDates = shift.getEmployee().getUnavailableDates();
-                    return unavailableDates.contains(shift.getStart().toLocalDate())
-                        // The contains() check is ignored for a shift ends at midnight (00:00:00).
-                        || (shift.getEnd().isAfter(shift.getStart().toLocalDate().plusDays(1).atStartOfDay())
-                                && unavailableDates.contains(shift.getEnd().toLocalDate()));
-                })
-                .penalize(HardSoftScore.ONE_HARD, EmployeeSchedulingConstraintProvider::getShiftDurationInMinutes)
+                .expand(shift -> shift.getEmployee().getUnavailableDates())
```
Comment (triceo) [inline java/employee-scheduling/src/main/java/org/acme/employeescheduling/solver/EmployeeSchedulingConstraintProvider.java]: Using `expand` is not necessary; I think you've done that, so that later in the `filter`, you can use a method reference. Is that a good enough reason to introduce a functionality that slows down the constraint and, arguably, makes it more complex to understand? In my opinion, it is not.

File: java/employee-scheduling/src/main/java/org/acme/employeescheduling/domain/Shift.java [hunk 2]
```diff
@@ -89,6 +96,41 @@ public void setEmployee(Employee employee) {
         this.employee = employee;
     }
 
+    @JsonIgnore
+    public boolean isOverlappingWith(Collection<LocalDate> dates) {
+        return !getOverlappingDatesForShift(dates).isEmpty();
+    }
```
Comment (triceo) [inline java/employee-scheduling/src/main/java/org/acme/employeescheduling/domain/Shift.java]: Although this is a simple way of implementing the requirement, it is also an anti-pattern. 

Let us not teach our users that abandoning incrementality and turning everything into collection processing is the right way of doing things; they already think that anyway. There is a simple rule of thumb when working with constraint streams: if you see a collection or a for-loop anywhere, you're probably doing it wrong.

You have to process each of `LocalDate` individually. You can use `flattenLast(...)` to get it out of the `Shift`. (Here, the use of `expand(...)` may actually be necessary.)

**Review by triceo — CHANGES_REQUESTED** [review]
Please figure out an incremental approach to the requirement.

**Comment by Christopher-Chianelli** [comment]
Note: the part before `penalize` **does not** need to change; shifts are less than 24 hours long, and availabilities are based on dates, so `shiftStart.date() == availability.date() || shiftEnd.date() == availability.date()` is true if and only if there any overlap.

File: java/employee-scheduling/src/main/java/org/acme/employeescheduling/solver/EmployeeSchedulingConstraintProvider.java [hunk 3]
```diff
@@ -75,49 +74,41 @@ Constraint atLeast10HoursBetweenTwoShifts(ConstraintFactory constraintFactory) {
...
-                        // The contains() check is ignored for a shift ends at midnight (00:00:00).
-                        || (shift.getEnd().isAfter(shift.getStart().toLocalDate().plusDays(1).atStartOfDay())
-                                && unavailableDates.contains(shift.getEnd().toLocalDate()));
-                })
-                .penalize(HardSoftScore.ONE_HARD, EmployeeSchedulingConstraintProvider::getShiftDurationInMinutes)
+                .join(Employee.class, equal(Shift::getEmployee, Function.identity()))
+                .flattenLast(Employee::getUnavailableDates)
+                .filter((shift, unavailableDate) -> shift.getOverlappingDurationInMinutes(unavailableDate) > 0)
+                .penalize(HardSoftScore.ONE_HARD,
+                        (shift, unavailableDate) -> (int) shift.getOverlappingDurationInMinutes(unavailableDate))
```
Comment (triceo) [inline java/employee-scheduling/src/main/java/org/acme/employeescheduling/solver/EmployeeSchedulingConstraintProvider.java]: In this case, I think that `expand(...)` actually has value. `getOverlappingDurationInMinutes()` has quite a lot of logic, which is now being run twice.

**Comment by zepfred** [comment]
Since both of you think `getOverlappingDurationInMinutes` should be calculated once, I'll accept Chris's suggestion about the filter operation.

File: java/employee-scheduling/src/main/java/org/acme/employeescheduling/solver/EmployeeSchedulingConstraintProvider.java [hunk 4]
```diff
@@ -75,49 +74,44 @@ Constraint atLeast10HoursBetweenTwoShifts(ConstraintFactory constraintFactory) {
...
-                    return unavailableDates.contains(shift.getStart().toLocalDate())
-                        // The contains() check is ignored for a shift ends at midnight (00:00:00).
-                        || (shift.getEnd().isAfter(shift.getStart().toLocalDate().plusDays(1).atStartOfDay())
-                                && unavailableDates.contains(shift.getEnd().toLocalDate()));
-                })
-                .penalize(HardSoftScore.ONE_HARD, EmployeeSchedulingConstraintProvider::getShiftDurationInMinutes)
+                .join(Employee.class, equal(Shift::getEmployee, Function.identity()))
+                .flattenLast(Employee::getUnavailableDates)
+                .filter((shift, unavailableDate) -> shift.getStart().toLocalDate().equals(unavailableDate)
+                        || shift.getEnd().toLocalDate().equals(unavailableDate))
```
Comment (triceo) [inline java/employee-scheduling/src/main/java/org/acme/employeescheduling/solver/EmployeeSchedulingConstraintProvider.java]: The filter body should be extracted to a method on `Shift` and reused; it's non-trivial logic which is repeated in 3 constraints.

File: java/employee-scheduling/src/main/java/org/acme/employeescheduling/domain/Shift.java [hunk 5]
```diff
@@ -89,6 +92,24 @@ public void setEmployee(Employee employee) {
...
+        LocalDateTime endDateTime = LocalDateTime.of(date, LocalTime.MAX);
+        return getOverlappingDurationInMinutes(startDateTime, endDateTime, getStart(), getEnd());
+    }
+
+    private long getOverlappingDurationInMinutes(LocalDateTime firstStartDateTime, LocalDateTime firstEndDateTime,
+            LocalDateTime secondStartDateTime, LocalDateTime secondEndDateTime) {
+        LocalDateTime maxStartTime = firstStartDateTime.isAfter(secondStartDateTime) ? firstStartDateTime : secondStartDateTime;
+        LocalDateTime minEndTime = firstEndDateTime.isBefore(secondEndDateTime) ? firstEndDateTime : secondEndDateTime;
+        long minutes = maxStartTime.until(minEndTime, ChronoUnit.MINUTES);
+        return minutes > 0 ? minutes : 0;
```
Comment (triceo) [inline java/employee-scheduling/src/main/java/org/acme/employeescheduling/domain/Shift.java]: Any reason why this can't return an `int`? I doubt there will ever be 2 billion minutes of overlap. (`long` causes casting in the `penalize(...)` calls.)

File: java/employee-scheduling/src/main/java/org/acme/employeescheduling/solver/EmployeeSchedulingConstraintProvider.java [hunk 6]
```diff
@@ -54,18 +52,19 @@ Constraint requiredSkill(ConstraintFactory constraintFactory) {
...
                 .asConstraint("Overlapping shift");
     }
 
     Constraint atLeast10HoursBetweenTwoShifts(ConstraintFactory constraintFactory) {
         return constraintFactory.forEachUniquePair(Shift.class,
-                        Joiners.equal(Shift::getEmployee),
-                        Joiners.lessThanOrEqual(Shift::getEnd, Shift::getStart))
-                .filter((firstShift, secondShift) -> Duration.between(firstShift.getEnd(), secondShift.getStart()).toHours() < 10)
+                equal(Shift::getEmployee),
+                Joiners.lessThanOrEqual(Shift::getEnd, Shift::getStart))
```
Comment (triceo) [inline java/employee-scheduling/src/main/java/org/acme/employeescheduling/solver/EmployeeSchedulingConstraintProvider.java]: Are you sure about `forEachUniquePair` here? It is useful, but not in situations where the order of the two elements actually matters, such as here.

Consider shifts A, B. This will produce [A, B], but not [B, A]. This clashes with `A.end() < B.start()`; some of the pairs will not be selected and therefore not penalized.

A well-written test will catch this.

**Review by triceo — CHANGES_REQUESTED** [review]
I think I found a bug in the constraints.

File: java/employee-scheduling/src/main/java/org/acme/employeescheduling/domain/Shift.java (hunk 5 above)
Comment (zepfred) [reply java/employee-scheduling/src/main/java/org/acme/employeescheduling/domain/Shift.java]: There is no reason to not return an `int`.

File: java/employee-scheduling/src/main/java/org/acme/employeescheduling/solver/EmployeeSchedulingConstraintProvider.java (hunk 6 above)
Comment (zepfred) [reply java/employee-scheduling/src/main/java/org/acme/employeescheduling/solver/EmployeeSchedulingConstraintProvider.java]: Let me double-check it.

Comment (zepfred) [reply java/employee-scheduling/src/main/java/org/acme/employeescheduling/solver/EmployeeSchedulingConstraintProvider.java]: Good catch! I'm able to reproduce it with the following test:

```
        constraintVerifier.verifyThat(EmployeeSchedulingConstraintProvider::atLeast10HoursBetweenTwoShifts)
                .given(employee1, employee2,
                        new Shift("1", DAY_END_TIME, DAY_START_TIME.plusDays(1), "Location", "Skill", employee1),
                        new Shift("2", DAY_START_TIME, DAY_END_TIME, "Location 2", "Skill", employee1))
                .penalizesBy(600);
```

Comment (zepfred) [reply java/employee-scheduling/src/main/java/org/acme/employeescheduling/solver/EmployeeSchedulingConstraintProvider.java]: I double-checked the other constraints, and they look good to me. Also, the Python version is already using the `Join` operation.

File: java/employee-scheduling/src/main/java/org/acme/employeescheduling/solver/EmployeeSchedulingConstraintProvider.java [hunk 7]
```diff
@@ -54,18 +52,18 @@ Constraint requiredSkill(ConstraintFactory constraintFactory) {
...
                 .asConstraint("Overlapping shift");
     }
 
     Constraint atLeast10HoursBetweenTwoShifts(ConstraintFactory constraintFactory) {
-        return constraintFactory.forEachUniquePair(Shift.class,
-                        Joiners.equal(Shift::getEmployee),
-                        Joiners.lessThanOrEqual(Shift::getEnd, Shift::getStart))
-                .filter((firstShift, secondShift) -> Duration.between(firstShift.getEnd(), secondShift.getStart()).toHours() < 10)
+        return constraintFactory.forEach(Shift.class)
+                .join(Shift.class, equal(Shift::getEmployee), Joiners.lessThanOrEqual(Shift::getEnd, Shift::getStart))
```
Comment (triceo) [inline java/employee-scheduling/src/main/java/org/acme/employeescheduling/solver/EmployeeSchedulingConstraintProvider.java]: One joiner is statically imported, the other isn't.
Let's either consistently do static imports, or consistently don't.

**Review by triceo — APPROVED** [review]
LGTM after the last comment is resolved.
